export const VIBRANT_COLORS = [
  '#A020F0', // Neon Purple
  '#FF4500', // Safety Orange
  '#008080', // Deep Teal
  '#FF69B4', // Hot Pink
  '#32CD32', // Electric Lime
  '#DC143C', // Crimson
  '#FFD700', // Gold
  '#4B0082', // Indigo
  '#87CEEB', // Sky Blue
  '#36454F', // Charcoal
  '#7B3F00', // Chocolate
  '#3EB489', // Mint
];

export const CARTOON_NICKNAMES = [
  'He-Man',
  'Doug Funnie',
  'Inspector Gadget',
  'Bugs Bunny',
  'Daffy Duck',
  'Mickey Mouse',
  'Donald Duck',
  'Goofy',
  'Popeye',
  'Fred Flintstone',
  'George Jetson',
  'Scooby-Doo',
  'Tom Cat',
  'Jerry Mouse',
  'Pink Panther',
  'Woody Woodpecker',
  'Yogi Bear',
  'Huckleberry Hound',
  'Quick Draw McGraw',
  'Snagglepuss',
  'Top Cat',
  'Magilla Gorilla',
  'Peter Potamus',
  'Secret Squirrel',
  'Atom Ant',
  'Space Ghost',
  'Birdman',
  'Blue Falcon',
  'Dynomutt',
  'Captain Caveman',
  'Hong Kong Phooey',
  'Jabberjaw',
  'Speed Buggy',
  'Wheelie',
  'Wonder Wheels',
  'Spider-Man',
  'Batman',
  'Superman',
  'Wonder Woman',
  'Flash',
  'Green Lantern',
  'Aquaman',
  'Iron Man',
  'Captain America',
  'Thor',
  'Hulk',
  'Black Widow',
  'Hawkeye',
  'Wolverine',
  'Storm',
  'Cyclops',
  'Jean Grey',
  'Beast',
  'Gambit',
  'Rogue',
  'Jubilee',
  'Professor X',
  'Magneto',
  'Leonardo',
  'Raphael',
  'Donatello',
  'Michelangelo',
  'Splinter',
  'Shredder',
  'Optimus Prime',
  'Bumblebee',
  'Megatron',
  'Starscream',
  'Lion-O',
  'Cheetara',
  'Panthro',
  'Tygra',
  'Mumm-Ra',
  'Skeletor',
  'She-Ra',
  'Orko',
  'Battle Cat',
  'Man-At-Arms',
  'Teela',
  'Evil-Lyn',
  'Beast Man',
  'Trap Jaw',
  'Mer-Man',
  'Ram Man',
  'Stratos',
  'Buzz-Off',
  'Fisto',
  'Sy-Klone',
  'Moss Man',
  'Roboto',
  'Zodac',
  'King Hiss',
  'Hordak',
  'Grizzlor',
  'Leech',
  'Mantenna',
  'Modulok',
  'Dragstor',
  'Multi-Bot',
  'Scorpia',
  'Shadow Weaver',
  'Catra',
  'Entrapta',
  'Frosta',
  'Glimmer',
  'Bow',
  'Kowl',
  'Loo-Kee',
  'Madame Razz',
  'Sea Hawk',
  'Swift Wind',
  // Simpsons
  'Homer Simpson',
  'Marge Simpson',
  'Bart Simpson',
  'Lisa Simpson',
  'Maggie Simpson',
  'Ned Flanders',
  'Mr. Burns',
  'Waylon Smithers',
  'Krusty the Clown',
  'Sideshow Bob',
  'Milhouse Van Houten',
  'Ralph Wiggum',
  'Chief Wiggum',
  'Apu Nahasapeemapetilon',
  'Barney Gumble',
  'Moe Szyslak',
  'Seymour Skinner',
  'Groundskeeper Willie',
  'Otto Mann',
  'Lenny Leonard',
  'Carl Carlson',
  // Family Guy
  'Peter Griffin',
  'Lois Griffin',
  'Stewie Griffin',
  'Brian Griffin',
  'Chris Griffin',
  'Meg Griffin',
  'Glenn Quagmire',
  'Cleveland Brown',
  'Joe Swanson',
  'Mayor Adam West',
  'Herbert',
  'Tom Tucker',
  'Diane Simmons',
  'Carter Pewterschmidt',
  'Babs Pewterschmidt',
  // South Park
  'Eric Cartman',
  'Stan Marsh',
  'Kyle Broflovski',
  'Kenny McCormick',
  'Butters Stotch',
  'Randy Marsh',
  'Sharon Marsh',
  'Shelly Marsh',
  'Liane Cartman',
  'Sheila Broflovski',
  'Gerald Broflovski',
  'Ike Broflovski',
  'Chef',
  'Mr. Garrison',
  'Mr. Mackey',
  'Officer Barbrady',
  'Big Gay Al',
  'Mr. Hankey',
  'Towelie',
  'Token Black',
  'Jimmy Valmer',
  'Timmy Burch',
  'Tweek Tweak',
  'Craig Tucker',
  'Clyde Donovan',
  'Wendy Testaburger',
  'Bebe Stevens',
];
